apiVersion: apps/v1
kind: Deployment
metadata:
  name: general-worker-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: worker
      type: general
  template:
    metadata:
      labels:
        app: worker
        type: general
    spec:
      containers:
      - name: worker
        image: almadsam/worker:latest  
        env:
        - name: WORKER_TYPE
          value: "general"
        ports:
        - containerPort: 8080
