apiVersion: v1
kind: Pod
metadata:
  name: worker-general
spec:
  containers:
  - name: worker
    image: almadsam/worker:latest
    env:
    - name: WORKER_TYPE
      value: "general"
    - name: PLANNER
      value: "http://planner:3000"  
    - name: PORT
      value: "8080"
