apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: almadsam/worker:latest
        env:
        - name: WORKER_TYPE
          value: "general"
        ports:
        - containerPort: 8080
